
import { jsPDF } from 'jspdf';
import { MentalHealthResult } from './mentalHealthAssessment';

export const generatePDF = (result: MentalHealthResult, userName: string) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('Emotional Well-being Overview', 20, 30);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated for: ${userName}`, 20, 40);
    doc.text(`Date: ${date}`, 20, 46);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 55, 190, 55);

    // Summary Section
    doc.setFontSize(16);
    doc.setTextColor(40, 40, 40);
    doc.text('User Summary', 20, 70);

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const splitInterpretation = doc.splitTextToSize(result.interpretation, 170);
    doc.text(splitInterpretation, 20, 80);

    // Insights Section
    doc.setFontSize(16);
    doc.text('Emotional Insights', 20, 110);

    doc.setFontSize(11);
    doc.text(`Anxiety Level: ${result.anxietyLevel}`, 30, 120);
    doc.text(`Depression Level: ${result.depressionLevel}`, 30, 128);
    doc.text(`Stress Level: ${result.stressLevel}`, 30, 136);
    doc.text(`Overall Distress: ${result.overallDistress}`, 30, 144);

    // Suggestions
    doc.setFontSize(16);
    doc.text('Recommended Steps', 20, 160);

    doc.setFontSize(11);
    result.tips.forEach((tip, index) => {
        doc.text(`• ${tip}`, 25, 170 + (index * 8));
    });

    // Footer Disclaimer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    const disclaimer = 'Disclaimer: This report is generated by an assistant and is NOT a medical diagnosis. If you are feeling overwhelmed or unsafe, please seek professional support or contact emergency services.';
    const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
    doc.text(splitDisclaimer, 20, 260);

    doc.save(`Mental_Health_Report_${userName.replace(/\s+/g, '_')}.pdf`);
};

export const generateDOC = (result: MentalHealthResult, userName: string) => {
    const date = new Date().toLocaleDateString();
    const content = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Mental Health Report</title>
    <style>
      body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
      h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
      h2 { color: #34495e; margin-top: 30px; }
      .meta { color: #7f8c8d; margin-bottom: 40px; }
      .insight-item { margin: 10px 0; padding-left: 20px; }
      .disclaimer { margin-top: 100px; font-size: 10px; color: #95a5a6; border-top: 1px solid #eee; padding-top: 20px; }
    </style>
    </head>
    <body>
      <h1>Emotional Well-being Overview</h1>
      <div class="meta">
        <p><strong>Generated for:</strong> ${userName}</p>
        <p><strong>Date:</strong> ${date}</p>
      </div>
      
      <h2>User Summary</h2>
      <p>${result.interpretation}</p>
      
      <h2>Emotional Insights</h2>
      <div class="insight-item"><strong>Anxiety Level:</strong> ${result.anxietyLevel}</div>
      <div class="insight-item"><strong>Depression Level:</strong> ${result.depressionLevel}</div>
      <div class="insight-item"><strong>Stress Level:</strong> ${result.stressLevel}</div>
      <div class="insight-item"><strong>Overall Distress:</strong> ${result.overallDistress}</div>
      
      <h2>Recommended Steps</h2>
      <ul>
        ${result.tips.map(tip => `<li>${tip}</li>`).join('')}
      </ul>
      
      <div class="disclaimer">
        <p>Disclaimer: This report is generated by an AI assistant and is NOT a medical diagnosis. If you are feeling overwhelmed or unsafe, please seek professional support or contact emergency services.</p>
      </div>
    </body>
    </html>
  `;

    const blob = new Blob(['\ufeff', content], {
        type: 'application/msword'
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Mental_Health_Report_${userName.replace(/\s+/g, '_')}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};
